id: oracle-ebs-credentials

info:
  name: Oracle E-Business System Credentials Page - Detect
  author: dhiyaneshDk
  severity: high
  description: Oracle E-Business System credentials page was detected.
  reference:
    - https://www.blackhat.com/docs/us-16/materials/us-16-Litchfield-Hackproofing-Oracle-eBusiness-Suite-wp-4.pdf
    - https://www.blackhat.com/docs/us-16/materials/us-16-Litchfield-Hackproofing-Oracle-eBusiness-Suite.pdf
    - http://www.davidlitchfield.com/AssessingOraclee-BusinessSuite11i.pdf
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  tags: config,exposure,oracle

requests:
  - method: GET
    path:
      - '{{BaseURL}}/OA_HTML/jtfwrepo.xml'

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "password="
          - "<PUSR_LIST>"
        part: body

      - type: word
        words:
          - "text/xml"
        part: header

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/22
