id: ovpn-config-exposed

info:
  name: OVPN Configuration Download Page - Detect
  author: tess
  severity: low
  description: OVPS configuration download page was detected.
  classification:
    cwe-id: CWE-200
  metadata:
    verified: "true"
    shodan-query: http.title:"OVPN Config Download"
  tags: config,ovpn,exposure

requests:
  - method: GET
    path:
      - '{{BaseURL}}'

    host-redirects: true
    max-redirects: 2
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - 'OVPN Config Download'
          - 'Config List'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/22
