id: php-fpm-config

info:
  name: PHP-FPM Configuration Page - Detect
  author: sheikhrishad
  severity: info
  description: PHP-FPM configuration page was detected.
  reference: https://www.php.net/manual/en/install.fpm.php
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  tags: config,exposure,php

requests:
  - method: GET
    path:
      - "{{BaseURL}}/php-fpm.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "FPM Configuration"
          - "Pool Definitions"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/22
