id: proxy-wpad-exposure

info:
  name: Web Proxy Auto-Discovery Configuration File - Detect
  author: DhiyaneshDk
  severity: info
  description: Web Proxy Auto-Discovery configuration file was detected.
  reference: https://en.wikipedia.org/wiki/Web_Proxy_Auto-Discovery_Protocol
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    verified: true
    shodan-query: html:"wpad.dat"
  tags: config,exposure,proxy

requests:
  - method: GET
    path:
      - "{{BaseURL}}/wpad.dat"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "FindProxyForURL"
          - "url"
          - "host"
        condition: and

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/03/02
