id: sftp-credentials-exposure

info:
  name: SFTP Credentials - Detect
  author: sheikhrishad
  severity: high
  description: SFTP credentials were detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  tags: config,ftp,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/sftp-config.json"
      - "{{BaseURL}}/ftpsync.settings"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "file_permissions"
          - "extra_list_connections"
        part: body
        condition: and

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
