id: ssh-known-hosts

info:
  name: SSH Known Hosts File - Detect
  author: geeknik
  severity: info
  description: SSH known hosts file was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  reference:
    - https://datacadamia.com/ssh/known_hosts
  tags: config,exposure,ssh

requests:
  - method: GET
    path:
      - "{{BaseURL}}/.ssh/known_hosts"
      - "{{BaseURL}}/.ssh/known_hosts.old"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "ssh-dss"
          - "ssh-ed25519"
          - "ssh-rsa"
          - "ecdsa-sha2-nistp256"
        condition: or

      - type: status
        status:
          - 200

# Enhanced by md on 2023/02/23
