id: svnserve-config

info:
  name: Svnserve Configuration File - Detect
  author: sheikhrishad
  severity: info
  description: Svnserve configuration file was detected.
  reference: https://linux.die.net/man/8/svnserve
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cvss-score: 0.0
    cwe-id: CWE-200
  metadata:
    verified: "true"
    google-query: intext:"configuration of the svnserve daemon"
  tags: config,exposure,svnserve

requests:
  - method: GET
    path:
      - "{{BaseURL}}/svnserve.conf"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "This file controls the configuration of the svnserve daemon"

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/03/02
