id: ventrilo-config

info:
  name: Ventrilo Configuration File - Detect
  author: geeknik
  severity: high
  description: |
    Ventrilo configuration file was detected, The file discloses the application's Adminpassword and Password.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  reference:
    - https://www.ventrilo.com/setup.php
  metadata:
    verified: true
  tags: ventrilo,config,exposure

requests:
  - method: GET
    path:
      - "{{BaseURL}}/ventrilo_srv.ini"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - "[Server]"
          - "Name"
          - "Phonetic"
        condition: and

      - type: word
        part: header
        words:
          - "text/plain"

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/03/02
