id: websheets-config

info:
  name: Websheets Configuration File - Detect
  author: geeknik
  severity: high
  description: Websheets configuration file was detected.
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N
    cvss-score: 7.5
    cwe-id: CWE-200
  reference:
    - https://github.com/daveagp/websheets
  metadata:
    verified: true
  tags: websheets,config,exposure,files

requests:
  - method: GET
    path:
      - '{{BaseURL}}/ws-config.json'
      - '{{BaseURL}}/ws-config.example.json'

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"db-password":'
          - '"db-database":'
        condition: and

      - type: status
        status:
          - 200

# Enhanced by cs on 2023/03/02
